version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./.docker_volume/logs:/code/logs
      - ./.docker_volume/static:/code/static

    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    networks:
      - hospital-management-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      -hospital-management-network

networks:
  hospital-management-network:
    driver: bridge
