version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./.docker_volume/logs:/code/logs
      - ./.docker_volume/static:/code/static

    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    networks:
      - clarke-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - clarke-network

networks:
  clarke-network:
    driver: bridge
